### ISSUE TITLE
Path in header

### ISSUE THREAD

**Issue by Arkezis** [MaxMelcher/AzureDevOps.WikiPDFExport#1]
Following discussion on your website, it would be really useful to have the "path" of the Markdown file in the header (or footer ?)

**Comment by MaxMelcher** [comment]
I agree, but putting the file names in there is complicated.

The PDF converter accepts an object for both header and footer with 3 properties: Left, Center, Right
How about having placeholders like [DATE] in there so you can parameter this? Current Page [PAGE] and Total Page [TOPAGE] are already built in by the PDF converter. That is implemented right now. 

For things like [PATH] that is being replaced with current wiki file path or [FILE] just with the filename things are a little different. They would have to be added to the html that is generated from the markdown files and then the PDF convert must pick it up and add it to the Header/Footer. I don't know if that is possible right now... you want to dig into it?

**Comment by Arkezis** [comment]
Yep, I looked into the code there is 2 ways. 
1/ We can use it as "header" and it can conflict with other ones (I need the [PATH] but some people may need others datas and the header can become very messy...)
2/ We can add the path in the title (as `h2`? )It can be optionnable which can be activated with `argument`).

I think the second option may be less intrusive :)

**Comment by MaxMelcher** [comment]
I’d go for 1) if I can figure out a way.
2) does not look great and is not flexible enough.

Check my last commit 0a81703 - I introduced 6 new parameters for header and footer. [date], [page], [toPage], [section] are replaced during runtime.

**Comment by MaxMelcher** [comment]
The approach with the JavaScript code could work: https://wkhtmltopdf.org/usage/wkhtmltopdf.txt

All built-in placeholder variables are documented there, too.

**Comment by MaxMelcher** [comment]
Tried it with the javascript approach - but the header rendering cannot access the page as it seems and therefore cannot get values from it. 
So coming back to your suggestion and adding the path as part of the content of the page similar to what I did with the --heading parameter. 
Commit will follow.

**Comment by MaxMelcher** [comment]
fixed in e541006311f618f45aa1da37d45e5472993b3aa8 - does that work for you @Arkezis ?

**Comment by Arkezis** [comment]
Looks nice but this only display the "name" and not the "path" :)
WikiPDFExporter.cs:203 should be something like `file.path` ?

**Comment by MaxMelcher** [comment]
did you use the "--pathToHeading" param?

**Comment by Arkezis** [comment]
Yep
https://docs.microsoft.com/fr-fr/dotnet/api/system.io.fileinfo?view=netframework-4.8 `FullName` should be better than `Name` :)

**Comment by MaxMelcher** [comment]
fullname could be really long - how about relative?

**Comment by Arkezis** [comment]
Sure, `relative` will be perfect (nobody need the `/home/MyAwesomeUser/Documents/blablabla/` ) :)

**Comment by MaxMelcher** [comment]
done

**Comment by Arkezis** [comment]
This is perfect ! 
Thanks a lot for your help :)
