### ISSUE TITLE
Old Mermaid-js Version

### ISSUE THREAD

**Issue by Nyhtfury** [MaxMelcher/AzureDevOps.WikiPDFExport#101]
I have a mermaid diagram that works in Azure DevOps (I presume cloud hosted, cannot find version), as well as an [online editor running Mermaid-js 8.14.0](https://mermaid-js.github.io/mermaid-live-editor/edit), but it doesn't work using this @ 4.2.3. Reviewing the code in this repository, it looks like mermaid support is through a hard-coded, minified JS file.

I'm happy the document still exports, but would rather have the diagram. Looking through release notes on the [Mermaid-js repository](https://github.com/mermaid-js/mermaid/releases?page=1), I thought it had something to do with nested subgraphs which was mentioned in the release of 8.8.1 on 9/30/2020 but removing the subgraph 'Region' still results in the same error.

Error Image Placeholder (with mermaid version, so that's neat):
![image](https://user-images.githubusercontent.com/24866162/157542150-d6a2aabe-d980-4fad-9b60-0aee1e459780.png)

Intended mermaid diagram:
![image](https://user-images.githubusercontent.com/24866162/157542604-ba911f81-4a6e-4e1c-9a90-6ce415593404.png)

Mermaid syntax to create above diagram:
> graph BT;
    subgraph Region
    subgraph "Subregion 1"
        O1{{Node 1}}
        O2{{Node 2}}
        O3{{Node 3}}
    end
    subgraph "Subregion 2"
        O4{{Node 4}}
        O5{{Node 5}}
        O6{{Node 6}}
    end
    end
    V{{VIP Node}} --- O1
    V --- O2
    V --- O3
    V ---- O4
    V ---- O5
    V ---- O6

**Comment by Nyhtfury** [comment]
Changing the lengths of connections to Node 4, 5, and 6 also did not change the outcome.

> V --- O4
V --- O5
V --- O6

**Comment by Nyhtfury** [comment]
My issue is resolved - it is indeed due to lengths of connections. When I'm contributing to my Azure DevOps wiki (git repository) it automatically contributes to the main branch. I have a separate branch I'm working in that has its own edits of the Pipeline's YAML file that I use written by [Richard Fennell](https://github.com/rfennell/AzurePipelines). I would love to have this issue with the enhancement tag.

**Comment by MaxMelcher** [comment]
i will change so that you can run with your own mermaid file.

**Comment by Nyhtfury** [comment]
Keeping this enhancement open.

**Comment by MaxMelcher** [comment]
Fixed with af0a226d787fe91314b2ab0a387ffbe754ba4d54
