### ISSUE TITLE
Header Compatibility

### ISSUE THREAD

**Issue by sebastiano-fuccio** [MaxMelcher/AzureDevOps.WikiPDFExport#102]
I've a Bundle header version compatibility check fail while I run the tool into an appropriate local repository.
Is this a known issue maybe happening for system compatibility (I'm running Win11)?

**Comment by MaxMelcher** [comment]
What’s a bundle header version compatibility check fail ?

**Comment by sebastiano-fuccio** [comment]
well ... I don't know, is the error message I get... Attaching a screenshot
![ErrorMsg](https://user-images.githubusercontent.com/64849339/159522556-903f59d3-d469-4489-840a-0042bcc63400.png)

**Comment by MaxMelcher** [comment]
What dotnet version do you have installed?

**Comment by LewisSC2** [comment]
I resolved this error by downloading the latest dotNET version.

**Comment by MaxMelcher** [comment]
Great!
