### ISSUE TITLE
[MacOs] Error on task download (sometimes)

### ISSUE THREAD

**Issue by Panda-Sharp** [MaxMelcher/AzureDevOps.WikiPDFExport#108]
Sometimes with a macos agent, the pipeline task fail on download with the following error

```
Starting download azuredevops-export-wiki-osx to /Users/runner/work/_temp
##[error]Forbidden
##[error]Forbidden
(node:1745) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, chmod '/Users/runner/work/_temp/azuredevops-export-wiki-osx'
Downloaded executable /Users/runner/work/_temp/azuredevops-export-wiki-osx
    at Object.chmodSync (fs.js:1027:3)
Set execute permission on executable /Users/runner/work/_temp/azuredevops-export-wiki-osx
    at /Users/runner/work/_tasks/WikiPdfExportTask_48d40d27-32e1-460e-8ea6-0dfb48abdd6f/2.6.2/ExportFunctions.js:135:20
    at Generator.next (<anonymous>)
    at fulfilled (/Users/runner/work/_tasks/WikiPdfExportTask_48d40d27-32e1-460e-8ea6-0dfb48abdd6f/2.6.2/ExportFunctions.js:5:58)
(node:1745) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1745) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Is there any hope for a fix?
thanks

**Comment by rfennell** [comment]
I have seen this problem in my testing. It appears to be an issue with the MAC Agents being unable to download the PDF tool from GitHub, a retry usually fixes it.

The most reliable workaround is to place the `azuredevops-export-wiki-osx` MAC exe in your own repo and avoid the need to download it from GitHub each time.

FYI: I can't ship the EXE within the Azure DevOps task as it makes the package too big

**Comment by rfennell** [comment]
No nothing special about running the process on a MAC or any other OS. It is the same code, the only difference being a switch statement to make sure the correct EXE is downloaded and run.

You can do all the rest of your CI/CD process with a MC agent, but have a job running on WIndows/Unix that does the PDF converison.

**Comment by Panda-Sharp** [comment]
Nothing special, just simplicity, if it would be possible/easy to fix it, would be really nice, if there is no hope, I'll run it on a different job with different agent 🙂

**Comment by MaxMelcher** [comment]
Thanks

**Comment by rfennell** [comment]
Tracked in https://github.com/rfennell/AzurePipelines/issues/1440

**Comment by MaxMelcher** [comment]
thanks @rfennell  - whats the maximum file size to include it into your task?

**Comment by rfennell** [comment]
The max size is only 25Mb for custom extensions, so way too small for most tools to be included. Space for just scripts
