### ISSUE TITLE
Formatting problem

### ISSUE THREAD

**Issue by chpo69** [MaxMelcher/AzureDevOps.WikiPDFExport#109]
Hello,

When I follow a line in bold and a table separated by one line, the table is not interpreted. If I add one more line it works. See the example below:

 `
**Test ok**
| a | b | c | d |
|--|--|--|--|
|  |  |  |  |
|  |  |  |  |
|  |  |  |  |

**Test nok**

| a | b | c | d |
|--|--|--|--|
|  |  |  |  |
|  |  |  |  |
|  |  |  |  |
`

![image](https://user-images.githubusercontent.com/45226763/166247116-f885e5ba-6c59-4535-a534-523c4d583e0d.png)

Thank you for your help

**Comment by cduivis** [comment]
This issue still reproduces
