### ISSUE TITLE
Mermaid not supported

### ISSUE THREAD

**Issue by itsallyours** [MaxMelcher/AzureDevOps.WikiPDFExport#11]
raw mermaid markup is used instead of the rendered graphic

**Comment by MaxMelcher** [comment]
cannot follow - can you send me a sample?

**Comment by MiroRadenovic** [comment]
Confirm mermaid js rendering is not implemented.
@MaxMelcher : https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops

**Comment by MaxMelcher** [comment]
Not yet - I can check if that is doable.
Happily accepting pull request for this :)

**Comment by MaxMelcher** [comment]
fixed!
