### ISSUE TITLE
Body-margins when using header/footer

### ISSUE THREAD

**Issue by Tobias-08** [MaxMelcher/AzureDevOps.WikiPDFExport#114]
Hi,

when header/footer is used the document body gets quite large margins (e. g. in the official example.pdf). This isn't the case when header/footer is off.

As the debug-html does not contain the header/footer this behaviour seems to be independent of the css and instead seems to appear in the puppeteer call? Is it possible to adjust the margins of the body?

Thanks!

**Comment by MaxMelcher** [comment]
Not sure if that is configurable - the header/footer options are super limited in puppeteer... 
Have you tried overriding the css of the main document?

**Comment by Tobias-08** [comment]
Yes, but with no success. Maybe I did something wrong...

**Comment by Tobias-08** [comment]
Update: Overriding in css works after all:

```
@page { margin-left: 1.2cm; margin-right: 1.2cm; margin-top: 1.8cm; margin-bottom: 1.8cm; }
```

That said: Are the `MarginOptions` in [PDFGenerator](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/blob/main/AzureDevOps.WikiPDFExport/PDFGenerator.cs) set on purpose? Maybe an adjustment (decrease) on that side could make the css workaround obsolete.
