### ISSUE TITLE
Print subsets of wiki

### ISSUE THREAD

**Issue by gcerik** [MaxMelcher/AzureDevOps.WikiPDFExport#117]
First of all - thanks - this tool is amazing. Saved me hours of assembling our wiki docs into a PDF, I can't believe all the fine details included like mermaid js diagrams, etc. 

Anyway the main feature I am missing is a way to print a subset. We have two key documents in our Wiki - each is one page with many subpages and ideally we'd like to export each one into a separate PDF. I guess one idea would be to specify a page name in the CLI?

I tried the single option but it does not include the child pages.

**Comment by MaxMelcher** [comment]
Thanks!

Are the subpages in the same folder hierarchy? Then you could use this as entrypoint. Or use https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport#--exclude-paths to exclude the others.
Or use the —filter and page tags?

It really depends a bit on your wiki structure.

Cheers,
Max

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: gcerik ***@***.***>
Sent: Friday, July 29, 2022 4:08:51 PM
To: MaxMelcher/AzureDevOps.WikiPDFExport ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MaxMelcher/AzureDevOps.WikiPDFExport] Print subsets of wiki (Issue #117)


First of all - thanks - this tool is amazing. Saved me hours of assembling our wiki docs into a PDF, I can't believe all the fine details included like mermaid js diagrams, etc.

Anyway the main feature I am missing is a way to print a subset. We have two key documents in our Wiki - each is one page with many subpages and ideally we'd like to export each one into a separate PDF. I guess one idea would be to specify a page name in the CLI?

I tried the single option but it does not include the child pages.
