### ISSUE TITLE
Images not working when using -p parameter

### ISSUE THREAD

**Issue by BlueChipDevelopment** [MaxMelcher/AzureDevOps.WikiPDFExport#12]
Images will not be added to the PDF when a path is used. When the .attachments from the rool folder is copied to the folder where the path directs to then it works again.

The tool should always look for attachments in the .attachments folder in the root folder.

**Comment by MaxMelcher** [comment]
do you have a sample?

**Comment by MaxMelcher** [comment]
I assume this is fixed by #29
