### ISSUE TITLE
Could not generate single file

### ISSUE THREAD

**Issue by minik42** [MaxMelcher/AzureDevOps.WikiPDFExport#126]
Hi, after new release I'm my pipeline stopped generating single file. I'm getting an error:
>System.ArgumentException: D:\a\1\s/docs/changelog.md not found
>   at azuredevops_export_wiki.SingleFileScanner.Scan()
 >  at azuredevops_export_wiki.WikiPDFExporter.Export()

Here is the command my pipeline was using:

>Using command '"D:\a\_temp\azuredevops-export-wiki.exe"  -p "D:\a\1\s" -s "D:\a\1\s/docs/changelog.md" -o "D:\a\1\a/PDF/changelog.pdf" --css "D:\a\1\s/docs/styles.css" -v'

**Comment by MaxMelcher** [comment]
@minik42 can you please check again? 
There might be an issue if you run it with -p and -s with different root folder.

**Comment by minik42** [comment]
Thank you, it's working perfectly now!
