### ISSUE TITLE
stdout maxBuffer length exceeded with debug flag

### ISSUE THREAD

**Issue by minik42** [MaxMelcher/AzureDevOps.WikiPDFExport#127]
Hi I encountered an error when using a --debug flag with big mardkown file

>##[error]RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded

**Comment by MaxMelcher** [comment]
How big is the markdown file?
Is a split possible as workaround ?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: minik42 ***@***.***>
Sent: Friday, October 14, 2022 10:19:22 AM
To: MaxMelcher/AzureDevOps.WikiPDFExport ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MaxMelcher/AzureDevOps.WikiPDFExport] stdout maxBuffer length exceeded with debug flag (Issue #127)


Hi I encountered an error when using a --debug flag with big mardkown file

##[error]RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded

**Comment by minik42** [comment]
Currently it has: 179743 characters.
Yeah we will split it probably

**Comment by MaxMelcher** [comment]
That’s a book in one file 😂

But I will add a test case for this, thanks for reporting!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
