### ISSUE TITLE
Allow a header page before the global table of contents page in the exported pdf file

### ISSUE THREAD

**Issue by sachinchitran** [MaxMelcher/AzureDevOps.WikiPDFExport#129]
When I try to export the wiki markdown files (with the global table of contents argument), the resulting PDF file shows the table of contents as the first page. I looked through the code and understand that the toc md file gets added to the top of the list of md files before the pdf conversion. Is it possible to have an option to choose an md file as the first page so that I do not have the table of contents as the first page? 

`azuredevops-export-wiki  -o "ReleaseNotes_20221012.1.pdf" --header-template-path "header.html" --footer-template-path "footer.html" --css "styles.css" --globaltoc "Table of contents" -v`

**Comment by minik42** [comment]
That should work now, try using --GlobalTOCPosition parameter

**Comment by MaxMelcher** [comment]
please try @minik42 solution or let us know if that is not working for you.
