### ISSUE TITLE
Getting a strange exception all of a sudden

### ISSUE THREAD

**Issue by jkellywilkerson** [MaxMelcher/AzureDevOps.WikiPDFExport#136]
![AzureDevOps_WikiExport_Error](https://user-images.githubusercontent.com/9677908/223496066-cacc96d7-203f-4ee3-b6e5-d4c11466152c.png)

This error appears when running the .exe from the Releases (latest version) as well as from a new Rebuild from source.

**Comment by MaxMelcher** [comment]
What parameters do you use? 
 The error indicates that the headless chrome installation is broken/missing.

**Comment by jkellywilkerson** [comment]
No parameter...pure double-click execution from Windows Explorer. It worked well like that back in December and stopped working suddenly. I've tried it on several different machines and not sure what else to try.

**Comment by jkellywilkerson** [comment]
Chrome is installed and set as the default browser. Not sure how to install/repair a "headless" version. But will see what Google says.

**Comment by jkellywilkerson** [comment]
Headless Chrome does work on the machine in question, but I still get the same error. This command does produces the expected PDF: chrome --headless --disable-gpu --print-to-pdf="C:\ChromeStatus.pdf" https://www.chromestatus.com/

Anything additional I can try?

**Comment by jkellywilkerson** [comment]
Pointing the executable directly to Chrome using the --chrome-path="<path to chrome.exe>" worked. Not sure what changed in the environment that would cause the "headless" option to stop working, but this appears to work:

azuredevops-export-wiki.exe --chrome-path="C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"

**Comment by MaxMelcher** [comment]
it might also work if you delete the Win64-901912... folder that stores the google chrome headless copy. the converter downloads a fresh copy and the issue should go away. 
Thanks for letting me know!
