### ISSUE TITLE
Mermaid charts are not rendered

### ISSUE THREAD

**Issue by NenoLoje** [MaxMelcher/AzureDevOps.WikiPDFExport#137]
When I use the tool using the Azure Pipelines task mermaid syntax (`:::mermaid`) does not get rendered as mermaid charts.

The resulting PDF looks like this:

![grafik](https://user-images.githubusercontent.com/13981145/229372387-c952eb72-713e-46a8-a157-777e13e64dcd.png)

Any idea what is going wrong here?

**Comment by bizdevops42** [comment]
I had the same issue. The mermaid diagrams get rendered by adding the option `-m` (e.g. on Windows  `azuredevops-export-wiki.exe -m`). Apparently the rendering of mermaid is not enabled by default. The option `-m/--mermaid` is only mentioned in the explanation for the `--chrome-path` configuration option.

**Comment by NenoLoje** [comment]
Does #61 include support for the Azure DevOps-style mermaid syntax?

**Comment by matthias-colt** [comment]
> ...That certainly helps. I'm now using --mermaid, but it seems it's not rendering the Azure DevOps wiki syntax,...

@NenoLoje For me the DevOps style`::: mermaid` actually works, using latest release 4.6.0. I have not specified the Chrome path, so it's using the headless version.

If I specify the Chrome path, the mermaid rendering doesn't work (I just get the text instead). 

Are you using normal installed Chrome or the headless version?
