### ISSUE TITLE
GlobalTOC is generated incorrectly

### ISSUE THREAD

**Issue by takinosaji** [MaxMelcher/AzureDevOps.WikiPDFExport#140]
Hi @MaxMelcher. Thank you for the tool you have created.

When GlobalTOC is enabled, the TOC content doesn't contain the links to the documents by name.

Consider the following wiki structure
wikiFolder/
 - page1.md (doesn't contain TOC)
 - page2.md (contains TOC)
 - page3.md (doesn't contain TOC)

The TOC output of the tool would be smth like this:
- page1
  - [headings from file page1.md]
- [headings from file page2.md]
- page3
  - [headings from file page3.md]

When the page contains its own TOC, the global TOC link to the page itself is omitted, and the whole TOC seems very weird. I tried the --heading parameter, but it doesn't affect the behavior.

**Comment by ivanignatiev** [comment]
I agree, the principle of heading organizing need more documentation.

Look like the tool only take in consideration headings in pages and not page titles.
