### ISSUE TITLE
Emoticons are too eager compared to AzureDevOps

### ISSUE THREAD

**Issue by cduivis** [MaxMelcher/AzureDevOps.WikiPDFExport#142]
When having the following md code:
`> **NOTE :** Testing`

This is how it renders on Azure DevOps:
![image](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/assets/3647813/115eed06-42ba-4fd1-b5aa-5d5e45496ab2)

This is how it renders in the exported PDF:
![image](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/assets/3647813/32509d1d-bd61-4f86-9d26-f1fc36e41fb6)

I would expect the output to be similar with Azure DevOps

**Comment by MaxMelcher** [comment]
Might be a pipeline issue - happy to merge a PR 👍
