### ISSUE TITLE
Option for HTML output (but without using --debug)

### ISSUE THREAD

**Issue by nbevans** [MaxMelcher/AzureDevOps.WikiPDFExport#145]
As title really. The --debug flag is great and all but it causes the HTML to be output to the stdout which, on a large file, can cause an error due to limited buffer size.

What is needed is a --store-html flag which retains just the specific behaviour of the --debug flag where it stores the .html file as part of the output.

Thanks

**Comment by MaxMelcher** [comment]
A PR would be great 👍
