### ISSUE TITLE
Data processing for PDF export

### ISSUE THREAD

**Issue by outorted** [MaxMelcher/AzureDevOps.WikiPDFExport#147]
Hi there,
I've received a request from a user to install this extension in order to export wiki articles to PDF. This sounds like a sensible idea :-). Since the wikis may include sensitive data, I would like to know how the processing works. Does the content of the wiki pages get sent somewhere to be processed, and then returned as a PDF? If so, please could you provide details? Is there a data privacy policy somewhere that I can forward on to our team?
Thanks

**Comment by MaxMelcher** [comment]
The tool does not need internet access - so the processing happens offline. 
For full disconnected mode you need to manually download chrome and add the correct parameters to it.
