### ISSUE TITLE
A name of pdf for each wiki file

### ISSUE THREAD

**Issue by olegsidokhmetov** [MaxMelcher/AzureDevOps.WikiPDFExport#149]
I create a wiki using "azuredevops-export-wiki" but after that I have one file "export.pdf" with 197 pages in it ‿︵ヽ(°□° )ノ︵‿

How can I create pdf pages separately so that each one has its own name? 

I saw that there is a parameter  https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport#-d----debug but  I tried it, and for me it does not working, I get the same one file with name export.pdf 

How to correctly use the `-b / --breakPage `parameter?

**Comment by MaxMelcher** [comment]
discussed offline:

-b starts a new page per file

If you want to create a pdf per markdown file, then use powershell to query all the files and run the converter for every page.
