### ISSUE TITLE
Inline HTML does not render correctly.

### ISSUE THREAD

**Issue by ahmadharis** [MaxMelcher/AzureDevOps.WikiPDFExport#17]
HTML code snippets inside wiki pages are not rendering correctly. This was working fine with the prior version of the code. I have noticed that MarkdownPipelineBuilder does not render the correct output if there is HTML embedded as code snippets.

A side effect of that is that our 276-page wiki export which was working correctly for the most parts (with a few imaging-related fixes that we made internally) only produces 50 pages now.

Sample Markdown and export attached for reference.
[Archive.zip](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/files/4511832/Archive.zip)

**Comment by MaxMelcher** [comment]
Thanks for the feedback - let me look into it.
