### ISSUE TITLE
Azure DevOps Extension in the Marketplace?

### ISSUE THREAD

**Issue by successhawk** [MaxMelcher/AzureDevOps.WikiPDFExport#20]
Have you created or are you aware of an Azure DevOps extension that is using this?
If not, have you considered creating one?
Have you done an initial assessment of what it would take?

**Comment by MaxMelcher** [comment]
No, not aware of an extension - I briefly checked it, the challenge would be to transfer the wiki files to a place were you can convert it. Doable, but out of scope for this tool.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rfennell** [comment]
Hi @MaxMelcher I had the same requirement as @successhawk, so I hope you don't mind but I have written an Azure DevOps wrapper for your excellent command line tool and published it to the [Azure DevOps Marketplace](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-WikiPDFExport-Tasks)

As well as my [WIKI based documentation](https://github.com/rfennell/AzurePipelines/wiki), I have put some more details in a [blog post](https://blogs.blackmarble.co.uk/rfennell/2020/08/27/exporting-release-notes-and-wikis-as-pdfs-using-a-new-azure-devops-extension-that-wrappers-azuredevops-wikipdfexport/) 

I have endeavoured to make sure your name and the links to the repo are prominent in the documentation, but if you need anything else just say

**Comment by MaxMelcher** [comment]
Hi Richard,

I already saw that and posted on your blog! Very cool, thanks! 

Do you mind adding parts of your blog post to the readme of this project? I think it helps more people to discover your extension. 

Thanks again,
Max

**Comment by rfennell** [comment]
Feel free to add any content or links you need

Richard
