### ISSUE TITLE
mermaid.min.js is not found if the tool is bundled into an exe

### ISSUE THREAD

**Issue by jkanczler** [MaxMelcher/AzureDevOps.WikiPDFExport#23]
Workaround for now: copy the mermaid.min.js file next to the executable, so it'll find the JavaScript in case of using -m option.

**Comment by MaxMelcher** [comment]
Thanks - that should be easy to fix

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jkanczler** [comment]
Yep, but I've created this issue to discuss the options.

I would prefer a new option too, `--mermaid-path` to be able to use a newer or older version of mermaid.js, if the consumer would like to this.

And if `--mermaid-path` is not defined, then the embedded can be used.

What do you think?

**Comment by MaxMelcher** [comment]
I'd say **--mermaidjs-path** follows the logic of **--chrome-path**. If not specified, download it. 

Another option could be to link to the online version here: 
`var mermaid = $"<script>{File.ReadAllText("mermaid.min.js")}</script>";`
and replace it with 
`var mermaid = $"<script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.6.4/mermaid.js"></script>";`

what you think?

**Comment by jkanczler** [comment]
Looks good for me. I'm going to implement it tonight and create a pull request.

**Comment by MaxMelcher** [comment]
Awesome 😎

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
