### ISSUE TITLE
.md files in sub-folders not converted to PDF

### ISSUE THREAD

**Issue by bubbletroubles** [MaxMelcher/AzureDevOps.WikiPDFExport#25]
I have a folder strucutre like

Repo
--> wiki folder
--> wiki.md file
------->product folder
------->product.md file

The wiki.md file is been written to PDF, but not the product.md file. 

Steps to reproduce:

Run
```
azuredevops-export-wiki.exe -path "wiki"
```

Using version azuredevops-export-wiki 2.5.1

**Comment by MaxMelcher** [comment]
Did you clone an Azure DevOps wiki or did you create your files manually?
If manually, then you need to create an .order file per folder containing the filename without extension.

--> wiki.md file
—>.order
------->product folder
------->product.md file
———>.order

The root level .order file would contain
wiki
product

The product folder .order file would contain
product

Does that help?

________________________________

**Comment by bubbletroubles** [comment]
adding the folder name to the .order file fixed it. Thanks for your help 👍

**Comment by MaxMelcher** [comment]
Happy to help! #closed

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
