### ISSUE TITLE
Ability to turn off telemetry

### ISSUE THREAD

**Issue by bubbletroubles** [MaxMelcher/AzureDevOps.WikiPDFExport#27]
The telemetry to Application Insights is an issue for our company - is there any way to turn off the telemetry?

**Comment by MaxMelcher** [comment]
can you try the latest release , I added a flag --disableTelemetry in b04bc3d to disable telemetry tracking.

To be clear, only the count of the pages and the execution time are tracked to ensure stable performance. 
In the case of an exception, the exceptions are tracked to reduce time to resolution.
