### ISSUE TITLE
Images are missing 

### ISSUE THREAD

**Issue by HeinzErnst** [MaxMelcher/AzureDevOps.WikiPDFExport#28]
I have images referenced like this:
<IMG src="http://xxx:8080/tfs/defaultcollection/491b8e66-79ee-4d6c-a116-3e4ca86a3c60/2c80f0d2-d14d-400c-a805-6f235ab18854/_api/_versioncontrol/itemContent?repositoryId=e4afb392-d795-4eed-afec-e276087b54b9&amp;path=.attachments%2Fimage-c2577efe-fd2b-4537-a445-9e047e944e5b.png&amp;version=GBwikiMaster&amp;contentOnly=true&amp;__v=5" alt="image.png"/>

They don't appear in the PDF.

**Comment by chucker** [comment]
I can't see your attached image, ironically. 😀

In our case, changing relative paths to explicitly start with `./` fixed it. For example:

```markdown
![Some alt text](./../My-Filename.png)
```

**Comment by MaxMelcher** [comment]
if you add the image as html img tag, please ensure that it does not require authentication - with the link you provided I assume the converter cannot download it and embed it into the pdf.

I tried it with a placeholder image and that worked:
`<img src="https://via.placeholder.com/150"/>`
