### ISSUE TITLE
Image sizing with width only

### ISSUE THREAD

**Issue by MJZawacki** [MaxMelcher/AzureDevOps.WikiPDFExport#30]
AzDo wiki's can support image scaling with the width only so the regex needs to handle the following sytax

![image text](../.attachments/image.png =500x)

**Comment by Diom** [comment]
I have the same issue.

**Comment by MaxMelcher** [comment]
let me check that one - I thought we had this fixed.

**Comment by MaxMelcher** [comment]
changed the regex and it supports now all combinations: 

### Pictures with Width/Height
![image.png](/.attachments/500.png =250x250)

### Pictures with Width only
![image.png](/.attachments/500.png =300x)

### Pictures with Height only
![image.png](/.attachments/500.png =x150)

**Comment by Diom** [comment]
I got back to generating docs this week, and I'm happy to say I tried all of the combinations successfully. Thanks!

**Comment by MaxMelcher** [comment]
Thanks for letting me know!
