### ISSUE TITLE
Big PNG images are not resized to fit page width

### ISSUE THREAD

**Issue by NinjaCross** [MaxMelcher/AzureDevOps.WikiPDFExport#32]
In my wiki I have a set of fairly big (2000x1000) PNG images.
They are embedded into the PDF file, but they exceed the page width (since they seems to be not resized to fit it)

**Comment by MaxMelcher** [comment]
You can provide a css file to control this behavior at least a little bit. 

[style.css](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/blob/main/styles.css):
`
img {
    max-width: 100%;
    max-height: 800px;
}
`
then launch the converter with flag --css with a path to the style.css file. 

does that help?

**Comment by NinjaCross** [comment]
> You can provide a css file to control this behavior at least a little bit.
> 
> [style.css](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/blob/main/styles.css):
> `img { max-width: 100%; max-height: 800px; }`
> then launch the converter with flag --css with a path to the style.css file.
> 
> does that help?

Thanks for the feedback and sorry tor my late response. I will try that ASAP.

**Comment by NinjaCross** [comment]
> > You can provide a css file to control this behavior at least a little bit.
> > [style.css](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/blob/main/styles.css):
> > `img { max-width: 100%; max-height: 800px; }`
> > then launch the converter with flag --css with a path to the style.css file.
> > does that help?
> 
> Thanks for the feedback and sorry tor my late response. I will try that ASAP.

I checked, it worked, thanks !

**Comment by MaxMelcher** [comment]
by the way - you can specify the size per image with the following syntax. Thats how it works in Azure DevOps.
![image.png](/.attachments/image.png =250x250)
