### ISSUE TITLE
Error during the export

### ISSUE THREAD

**Issue by yfrindel** [MaxMelcher/AzureDevOps.WikiPDFExport#34]
Hello,

When I try to export a wiki, I have the following error :

![image](https://user-images.githubusercontent.com/22955005/103903876-c7dc0d00-50fc-11eb-967e-44f2a0a538b7.png)

Do you have an idea why?

Other question, Is it possible to export a specific folder of the wiki? (because I just need to export a part of the wiki)

Thx

**Comment by yfrindel** [comment]
It seems working if I specify "--attachments-path .attachments"

**Comment by MaxMelcher** [comment]
-p and then the path to the subfolder will export only the pages below.

**Comment by yfrindel** [comment]
If I specify the subfolder, it's not correct because I have still the whole wiki exported : 
![image](https://user-images.githubusercontent.com/22955005/103920125-31fead00-5111-11eb-97c6-e56e666b4492.png)
![image](https://user-images.githubusercontent.com/22955005/103920280-607c8800-5111-11eb-9127-10c29a708626.png)

And if I add the -p parameter I have an error (because it's specify twice) : 
![image](https://user-images.githubusercontent.com/22955005/103920457-a0dc0600-5111-11eb-97bc-523a4ddd0661.png)
![image](https://user-images.githubusercontent.com/22955005/103920635-d385fe80-5111-11eb-9ebc-83af4523ec1e.png)

So for the moment it's not possible to export only a subfolder
