### ISSUE TITLE
Impossible to specify a subfolder

### ISSUE THREAD

**Issue by yfrindel** [MaxMelcher/AzureDevOps.WikiPDFExport#35]
The tool azuredevops-export-wiki.exe allow to the user to export as a PDF all the repo or a part of the repo.
I tried to export only a part of the repo with the following command line and it works : 
![image](https://user-images.githubusercontent.com/22955005/103910996-cb27c680-5105-11eb-8146-912c9d3b567f.png)

But with the azure devop extension, it's only possible to export the whole wiki. So, according to me, a new field is required with the path of the folder to export in the wiki (if empty that means all the wiki, and if a folder is specified only this folder).

Normally it's easy to implement because you have only to concatenate the folder name to the path (-o path/folder)

**Comment by MaxMelcher** [comment]
normally I would have sent you to the extension author - but he has sent you to me... :) 

So, I briefly tested the extension with my test wiki and I can provide the same parameters and the export worked for a subfolder:
![image](https://user-images.githubusercontent.com/1029559/105169768-4e8ce300-5b1c-11eb-9d05-df6733f4379b.png)

"AzureDevOps.WikiPDFExport" is a subfolder of my wiki that I wanted to export and I can provide that in the second "Local Folder" field of the extension task. This is then converted to the -p flag of the converter.

Does that help?
