### ISSUE TITLE
Images not found

### ISSUE THREAD

**Issue by yfrindel** [MaxMelcher/AzureDevOps.WikiPDFExport#38]
All the images with a blank in the name file are missing : 

![image](https://user-images.githubusercontent.com/22955005/104298755-a7c59880-54c4-11eb-9b1c-db8f4ec70163.png)

![image](https://user-images.githubusercontent.com/22955005/104298958-e3f8f900-54c4-11eb-84ce-d6afe4843313.png)

**Comment by MaxMelcher** [comment]
please test the latest version
