### ISSUE TITLE
Include / Exclude capabilities and multi output

### ISSUE THREAD

**Issue by cedrox** [MaxMelcher/AzureDevOps.WikiPDFExport#39]
Wiki is the perfect place to concentrate all the documentation. It would be great to add a tag capabilities to flag wiki pages. The aim here is to create mutliple pdf (for different audience for example)

_Idea about behavior_ : Flag page directly into md. Tag like 
```
---
tags:
- WelcomeGuide
- HDL
- SecurityGuideline
--- 
```

will output 3 different pdf with page inside.
- WelcomeGuide.pdf
- HDL.pdf
- SecurityGuideline.pdf

To avoid read of md file for each run, new argument should be added...

Thanks for the great share !

**Comment by cedrox** [comment]
Another solution would be to create a custom order file... (avoid to read all md file during the creation of List<MarkdownFile>)
The program would read the .order file but also all the file beginning with dot in the root folder : .export1, export2...
This solution would impose to create this .export1 file in sub folder to Include or Exclude sub files... 
Maybe harder to use and maintain
Thanks

**Comment by MaxMelcher** [comment]
I could imagine a "--filter" flag that includes pages only if they match the filter. I wasn't aware that the frontmatter is visualized in DevOps at all, so I guess this is a good usecase...
![image](https://user-images.githubusercontent.com/1029559/105165420-9ad52480-5b16-11eb-9f30-58e1fd3556d1.png)

Not sure when this will be added tho - PR anyone?
