### ISSUE TITLE
Add a Chocolatey package for the exe

### ISSUE THREAD

**Issue by sumo300** [MaxMelcher/AzureDevOps.WikiPDFExport#4]
It'd be great if you created a Chocolatey package with the latest release of this tool.  We use Chocolatey on our build servers to add additional command-line tools that can be used by Azure Pipelines.

This also might be a first step to creating an Azure Pipelines task to run this tool.

**Comment by MaxMelcher** [comment]
Doable, but have you tried this? https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/blob/master/AzureDevOps.WikiPDFExport/Build-Task.md

I will soon update it so it downloads the latest release of github.

**Comment by sumo300** [comment]
> Doable, but have you tried this? https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/blob/master/AzureDevOps.WikiPDFExport/Build-Task.md
> 
> I will soon update it so it downloads the latest release of github.

Apologies.  I didn't READ far enough.  :)
