### ISSUE TITLE
Images with relative path are not shown

### ISSUE THREAD

**Issue by MaxMelcher** [MaxMelcher/AzureDevOps.WikiPDFExport#42]
Added via drag and drop on a sub-page:
![Document](../../.attachments/icon_document.png =25x25)

**Comment by kbilkhoo** [comment]
Hi just to add to this, I also have issues with images, In my case tthe following does not work;

1. have a field in a feature workitem ( releasenotetext), I have formatted text and also copied/pasted an image.
2. pipeline that runas a query extract the text from the field and generates a markdown file and also generates a pdf file using the WikiPDFExporter
3.  inside the markdown file i have a link to the generated pdf file.
4. When I click download the images are missing.

I can view the images inside the markdown, but they are not showing in the pdf, the link to the images are formatted as follows:

<img src="https://dev.azure.com/xxxxx/19388173-189a-4e34-b77d-81cf49dae506/_apis/wit/attachments/e1312dbb-b0dd-442a-b447-33621d949004?fileName=image.png"

thankyou

**Comment by MaxMelcher** [comment]
> Hi just to add to this, I also have issues with images, In my case tthe following does not work;
> 
> 1. have a field in a feature workitem ( releasenotetext), I have formatted text and also copied/pasted an image.
> 2. pipeline that runas a query extract the text from the field and generates a markdown file and also generates a pdf file using the WikiPDFExporter
> 3. inside the markdown file i have a link to the generated pdf file.
> 4. When I click download the images are missing.
> 
> I can view the images inside the markdown, but they are not showing in the pdf, the link to the images are formatted as follows:
> 
> <img src="https://dev.azure.com/xxxxx/19388173-189a-4e34-b77d-81cf49dae506/_apis/wit/attachments/e1312dbb-b0dd-442a-b447-33621d949004?fileName=image.png"
> 
> thankyou

This is a different issue, created #48
