### ISSUE TITLE
Configuration option not working or out of date

### ISSUE THREAD

**Issue by Jheronymus** [MaxMelcher/AzureDevOps.WikiPDFExport#45]
Noticed that the configuration option -d is mentioned twice. Once for --date, once for --debug.
https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport#-d----date

**Comment by MaxMelcher** [comment]
Thanks, will update it.
the --date is no longer required, can be added via the --footer/--header flags and placeholders.

**Comment by MaxMelcher** [comment]
fixed.
