### ISSUE TITLE
Not building entire wiki

### ISSUE THREAD

**Issue by Jheronymus** [MaxMelcher/AzureDevOps.WikiPDFExport#46]
I've just created a new 'wiki as code' in DevOps and added a few files. Some link to each other.
I was hoping the tool would just add those a big PDF. How is this handeld?

If I run the tool in the folder, I get one empty page.
If I use the configuration option -s to refer to the individual markdown pages, they render fine.

How is the order/sorting and selecting of the files handled? Do they need to contain some form of meta data or reference?

**Comment by MaxMelcher** [comment]
If you edit the wiki in Azure DevOps directly it creates an .order text file that contains the sort order of the pages. The converter reads the .order file and then builds the pdf. 

You can create the .order file by yourself or try edit one wiki page in Azure DevOps and see if it's created by the Webapp.

**Comment by Jheronymus** [comment]
Ah, indeed. After creating a subpage and shifting the files around I ended up with a .order in the root and in the subfolder. This solved the problem indeed. Thanks for the fast reply.
