### ISSUE TITLE
Maybe TOC support possible

### ISSUE THREAD

**Issue by Jheronymus** [MaxMelcher/AzureDevOps.WikiPDFExport#47]
Hi, 

Was just browsing through the dependencies and noticed that the wkhtmltopdf has a newer version with a bug resolved regarding TOC. 

https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.6

This library is used in https://github.com/rndusr0/DinkToPdf

I don't have the full build setup yet, but this worth investigating

**Comment by MaxMelcher** [comment]
I checked the 0.12.6 version - it is in this wrapper: https://github.com/HakanL/WkHtmlToPdf-DotNet
But it does not render images with a relative path and TOC does not render.
