### ISSUE TITLE
Tables are not showing correctly in PDF Export

### ISSUE THREAD

**Issue by Sandafoks** [MaxMelcher/AzureDevOps.WikiPDFExport#51]
Hello,

when I export the PDF document the tables are not showing correctly. 

In Azure Wiki the tables are shown properly. See image below.
![image](https://user-images.githubusercontent.com/78953128/107744988-e9d83900-6d13-11eb-815f-60bca69e9aa9.png)

When I export the PDF the table looks like this:
![image](https://user-images.githubusercontent.com/78953128/107745056-fd839f80-6d13-11eb-8a92-f4fc59507c8f.png)

It just shows me the code I used in the Wiki.

Any help would be appreciated :).

Kind regards,

Alex

**Comment by MaxMelcher** [comment]
Hi alex - can you share parts of the table code so I can test this? In general tables should work.

**Comment by Sandafoks** [comment]
Hi Max,

sure I can.

`| Pin Nummer | Pin Name | Funktion | Signalrichtung |
|--|--|--|--|
| 1, 10, 19, 28, 37, 46 | GND | Ground | - |
| 47, 49 | VCC | +5VDC <br> Versorgungsspannung| - |
| 2...9; <br> 11...15;<br> 17, 51, 52 | A0...A15 | 16-Bit<br> Adressbuss | Eingang |
| 38 | /CS | Chipselect | Eingang (Low active) |
| 39 | /RD | Read Befehl | Eingang (Low active) |
| 43 | Sync1 | Resettakt | Ausgang |
| 45 | /Busy | Briefmarke aktiv | Ausgang (Low active) |
| 20...27;<br>29...36 | D0...D15 | 16-Bit <br>Datenbus | Ein-/Ausgang |
| 41 | /BHE | Byte High Enable <br> für 16-Bit Adressierung | Eingang (Low active) |
| 40 | /WR | Write Befehl | Eingang (Low active) |`

In Wiki it looks like this:

| Pin Nummer | Pin Name | Funktion | Signalrichtung |
|--|--|--|--|
| 1, 10, 19, 28, 37, 46 | GND | Ground | - |
| 47, 49 | VCC | +5VDC <br> Versorgungsspannung| - |
| 2...9; <br> 11...15;<br> 17, 51, 52 | A0...A15 | 16-Bit<br> Adressbuss | Eingang |
| 38 | /CS | Chipselect | Eingang (Low active) |
| 39 | /RD | Read Befehl | Eingang (Low active) |
| 43 | Sync1 | Resettakt | Ausgang |
| 45 | /Busy | Briefmarke aktiv | Ausgang (Low active) |
| 20...27;<br>29...36 | D0...D15 | 16-Bit <br>Datenbus | Ein-/Ausgang |
| 41 | /BHE | Byte High Enable <br> für 16-Bit Adressierung | Eingang (Low active) |
| 40 | /WR | Write Befehl | Eingang (Low active) |

**Comment by MaxMelcher** [comment]
I just checked it - is there a reason why the table is on one line? 

If you split the table in new lines, then it works correctly:

![image](https://user-images.githubusercontent.com/1029559/109436424-c0135780-7a1f-11eb-8108-5414bda2aaae.png)

![image](https://user-images.githubusercontent.com/1029559/109436429-c9042900-7a1f-11eb-8563-c730fd0aef99.png)

**Comment by Sandafoks** [comment]
Ok there is a progress. The content of the table is kind of formatted now. But the table lines are still missing. This is so weird because Azure is showing me the table lines.

![2021-03-01 08_18_37-export pdf](https://user-images.githubusercontent.com/78953128/109464476-0213bc00-7a67-11eb-9a19-f2d29df1f0f0.png)

What exactly do you mean by one line? I use the table tool in Azure to create a table and insert my text. In the Wiki editor it is not in one line (as you can see in the image above). 
I even added a new 3x2 table now without inserting any text. Even that table won't show up in code. It is just blank. It doesn't even matter if use the "Format tables" function in Azure wiki.

Could it be a "style.css" problem? 

This is my style.css .


body {
    font-family: "Segoe UI Emoji", Tahoma, Geneva, Verdana, sans-serif;
    font-size: 10pt;
}

h1 {
    font-size: 25pt;
}

h2 {
    font-size: 20pt;
}

h3 {
    font-size: 15pt;
}

h4 {
    font-size: 12pt;
}

img {
    max-width: 100%;
    max-height: 800px;
}

**Comment by MaxMelcher** [comment]
Yes I think it's css, I don't see table borders defined there. 

For the Screenshots above I used: 
https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/blob/main/devopswikistyle.css

**Comment by Sandafoks** [comment]
I used your css and it worked fine. Thank you very much for the fast support!
