### ISSUE TITLE
Folders are not rendered

### ISSUE THREAD

**Issue by casperease** [MaxMelcher/AzureDevOps.WikiPDFExport#52]
When you render a directory structure in the wiki, it will include subfolders.
Subfolders are not rendered by this tool.

**Comment by MaxMelcher** [comment]
Do you have .order files in your file system? They are created by Azure DevOps to correctly sort the pages/subfolder.

**Comment by casperease** [comment]
It correctly renders folders, if elements therein are correctly in .order files.
