### ISSUE TITLE
[[_TOC_]] is not supported

### ISSUE THREAD

**Issue by maxv15** [MaxMelcher/AzureDevOps.WikiPDFExport#53]
[[\_TOC\_]] that is the shortcut to generate "Table of Contents" in Azure DevOps Wiki is not supported by the export tool.
In the PDF [[\_TOC\_]] remains "[[\_TOC\_]]" instead of show the contents as in Wiki.

**Comment by MaxMelcher** [comment]
Yes, can’t fix that of now. Listed in the limitations: 
https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport#limitations

**Comment by dgitw** [comment]
How about suppressing TOC tag in the output in lieu of a fix?

**Comment by MaxMelcher** [comment]
fair and fixed- will be in Version 3.
