### ISSUE TITLE
Text looks squished together

### ISSUE THREAD

**Issue by thkn-hofa** [MaxMelcher/AzureDevOps.WikiPDFExport#54]
Hi,

The exported PDF looks like the text is squished together:

![image](https://user-images.githubusercontent.com/49520637/110524318-858e7680-8113-11eb-833b-162351561377.png)

Is it something I did wrong or is it a known issue? Either way: can it be fixed?

This was on 2.9.0, did not test any other versions.

Best regards,
Thomas

**Comment by MaxMelcher** [comment]
Please use the —css flag and provide the path to a Stylesheet, e.g to devopswikistyle.css that you will find in the repository.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: thkn-hofa ***@***.***>
Sent: Tuesday, March 9, 2021 8:14:08 PM
To: MaxMelcher/AzureDevOps.WikiPDFExport ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MaxMelcher/AzureDevOps.WikiPDFExport] Text looks squished together (#54)


Hi,

The exported PDF looks like the text is squished together:

[image]<https://user-images.githubusercontent.com/49520637/110524318-858e7680-8113-11eb-833b-162351561377.png>

Is it something I did wrong or is it a known issue? Either way: can it be fixed?

This was on 2.9.0, did not test any other versions.

Best regards,
Thomas

**Comment by thkn-hofa** [comment]
Oh God, what a simple solution. My Apologies for wasting your time.

Thank you for all the work!

**Comment by MaxMelcher** [comment]
No worries, you are not the first who does not like the default rendering. 

In version 3 I am going to change the default to have a better experience if you do not provide the css by yourselve.

Thanks,
Max
