### ISSUE TITLE
Usage in a Build Task

### ISSUE THREAD

**Issue by gmoed** [MaxMelcher/AzureDevOps.WikiPDFExport#56]
The URL link to download the exe in a build task is directing to an old version (2.1), its in the instructions found in this site

https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/blob/v2.9.0/AzureDevOps.WikiPDFExport/Build-Task.md

**Comment by MaxMelcher** [comment]
Yes, I will fix that.

 Can you use this extension - that handles everything for you:
https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-WikiPDFExport-Tasks



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: gmoed ***@***.***>
Sent: Friday, March 19, 2021 6:22:32 AM
To: MaxMelcher/AzureDevOps.WikiPDFExport ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MaxMelcher/AzureDevOps.WikiPDFExport] Usage in a Build Task (#56)


The URL link to download the exe in a build task is directing to an old version (2.1), its in the instructions found in this site

https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/blob/v2.9.0/AzureDevOps.WikiPDFExport/Build-Task.md

**Comment by gmoed** [comment]
awesome,, will give it a try. Thanks!
