### ISSUE TITLE
Add support for HeaderURL and hiding headerline

### ISSUE THREAD

**Issue by roel4ez** [MaxMelcher/AzureDevOps.WikiPDFExport#6]
Both wkhtmltopdf and DinkToPdf support the `header-url` and `header-line` arguments.

Can it also be supported in WikiPDFExport?

**Comment by MaxMelcher** [comment]
Sure - you want to submit a pull request?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by roel4ez** [comment]
Already done 😄

**Comment by MaxMelcher** [comment]
released via GH-7 - thanks!
