### ISSUE TITLE
Footer rendered differently in v3

### ISSUE THREAD

**Issue by Jheronymus** [MaxMelcher/AzureDevOps.WikiPDFExport#66]
Hi,
I just noticed that the footer is rendered differently when moving from version 2.9.0 to 3.0.0

Version V2.9.0
![image](https://user-images.githubusercontent.com/2046231/120661199-58d6ca80-c488-11eb-89d0-33e998e46b2e.png)

Version V3.0.0
![image](https://user-images.githubusercontent.com/2046231/120661271-668c5000-c488-11eb-9253-f01827aa3ac3.png)

Those screenshots were from Acrobat, in the Edge browser the footer looks even worse:
![image](https://user-images.githubusercontent.com/2046231/120661651-c256d900-c488-11eb-9928-763d9fb73974.png)

I think the inline styling is ignored. Or the stylesheet is now applied later and also to the header and footer
I could not find any logging on the header/footer generation using the -v and --debug options.

I'm using the (undocumented) --header-url and --footer-url to link to the files

full command
`& ".\azuredevops-export-wiki.exe" -v -o export.pdf --debug --css .\devopswikistyle.css --header-url .\page-header.html --footer-url .\page-footer.html -b -m`

Code:
```html
<!DOCTYPE html>
<html>

<head>
    <script>
        function subst() {
            var vars = {};
            var query_strings_from_url = document.location.search.substring(1).split('&');
            for (var query_string in query_strings_from_url) {
                if (query_strings_from_url.hasOwnProperty(query_string)) {
                    var temp_var = query_strings_from_url[query_string].split('=', 2);
                    vars[temp_var[0]] = decodeURI(temp_var[1]);
                }
            }
            var css_selector_classes = ['page', 'frompage', 'topage', 'webpage', 'section', 'subsection', 'date', 'isodate', 'time', 'title', 'doctitle', 'sitepage', 'sitepages'];
            for (var css_class in css_selector_classes) {
                if (css_selector_classes.hasOwnProperty(css_class)) {
                    var element = document.getElementsByClassName(css_selector_classes[css_class]);
                    for (var j = 0; j < element.length; ++j) {
                        element[j].textContent = vars[css_selector_classes[css_class]];
                    }
                }
            }
        }
    </script>
</head>

<body style="border:0; margin: 0;" onload="subst()">
    <table style="width: 100%">
        <tr><td style="text-align:left; font-size: small">Document generated on: <span class="date"></span></td>
            <td style="text-align:right">
                Page <span class="page"></span> of <span class="topage"></span>
            </td>
        </tr>
    </table>
</body>

</html>
```

**Comment by MaxMelcher** [comment]
Most likely a css thing - the footer has not changed. Are you using the same parameters for both converters?

**Comment by Jheronymus** [comment]
Yes, I specifically downloaded v2.9.0 to retest and verify the results.
I'll test tomorrow if the stylesheet is now global to the document, which I thought it wasn't (hence the online styling). If it is, that's actually an improvement.

**Comment by MaxMelcher** [comment]
Not sure, let me know what you find out

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jheronymus** [comment]
Just tested this by adding a class to my header/footer and put the styling (font color) for this class in the css file that gets passed in.
The result is as I expected:
- The styling is applied in v3.0.0
- The styling **not** applied in v2.9.0

This concludes that the passed in stylesheet is now global to the whole document. I would consider this a feature, not a bug. But maybe good to mention this and/or update the example header/footer files.

**Comment by MaxMelcher** [comment]
Thats nice - let's update the docs and css then

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jheronymus** [comment]
I'm getting inconsistent results when trying to make the bottom table 100% width again. Not sure about the total generated HTML. Is there a way to output that? The --debug gives the pages, but does not include the header/footer.
Moving inline styles to class on the same attribute does not give the same results. Which leads me to believe some other inline styling is added?

**Comment by Jheronymus** [comment]
I fixed my own document now. The only thing I can't seem to figure out is why all table cells have 0 padding. (this is throughout the document. The v2.9.0 html output had the stylesheet in the header. The v3.0.0 just has bare HTML. If you add the style sheet, the browser shows the tables with some padding, but this is not reflected in the PDF.

**Comment by MaxMelcher** [comment]
I tried to make the example a little bit better and document the parameters that were missing.
The header and footer html is really tricky.

header:
![image](https://user-images.githubusercontent.com/1029559/120870261-c3772b80-c598-11eb-881f-4c1c869af9c0.png)

footer: 
![image](https://user-images.githubusercontent.com/1029559/120870274-ca9e3980-c598-11eb-8044-444fc72a15f4.png)

The inherit the css, otherwise the icons would not work there.

**Comment by MaxMelcher** [comment]
can we close this?

**Comment by Jheronymus** [comment]
yeah, I think so. I still have some issues with the layouting, but will try with the newer version and extended logging.
