### ISSUE TITLE
Add formula (LaTeX) conversion

### ISSUE THREAD

**Issue by mcologne** [MaxMelcher/AzureDevOps.WikiPDFExport#67]
It would be nice to have formula, written in LateX, converted. Right now it is exported as plain text. DevOps displays the formulas nicely.

Thank you very much!

**Comment by MaxMelcher** [comment]
Can you check the latest version? I noticed that the rendering is not perfect, but I do not know why the fraction line is not visible...

**Comment by mcologne** [comment]
Thanks for your quick answer! Sorry, I didn't check the latest version.

Perfect, the latest version looks good. Greate work!!!

Additionally to the fraction line the integral is aligned too high vertically:
![grafik](https://user-images.githubusercontent.com/54852950/122531148-85115000-d01f-11eb-8e75-bf07bd6898d2.png)

**Comment by MaxMelcher** [comment]
in the version 4 this looks way better... 
[export.pdf](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/files/7033364/export.pdf)

**Comment by MaxMelcher** [comment]
improved in 81c469804fbdb917896076b929e3a80edcc3f833 - will be better in version 4.
