### ISSUE TITLE
include or exclude frontmatter

### ISSUE THREAD

**Issue by Jheronymus** [MaxMelcher/AzureDevOps.WikiPDFExport#69]
Frontmatter is used as meta data for the markdown file. So it might not always be appropriate in the final document.
Some other markdown parsers (that for instance generate a flat website) would also not do it, but details there could influence the page behavior.

I see two options.
1. A parameter to include/exclude the frontmatter in the PDF (possible a quickfix?)
2. A meta keyword in the frontmatter that allows you to configure this for every page. (a bit like how CSS media queries work). I guess there is some kind of standard for this out there. Let me know if you need info on this.

**Comment by MaxMelcher** [comment]
--no-frontmatter in version 4 removes the YAML tags / frontmatter from the pdf.
