### ISSUE TITLE
Generate a global table of content

### ISSUE THREAD

**Issue by AltarBeastiful** [MaxMelcher/AzureDevOps.WikiPDFExport#71]
It would be pretty useful to generate a global table of contents using all pages titles, like it's already done using bookmarks.
It would allow to add a page at the beginning of the document with all titles, page number and links. 
Kinda like what pandoc is doing with `--toc`

**Comment by MaxMelcher** [comment]
It's also on my wishlist, but lacking time, need to prio other things.

Would happily merge pull request - most of the functions is already in there... 😀

**Comment by chrPetry** [comment]
Would also like to see "outlines" in PDF.
Seems there are solutions:
https://gitlab.pagedmedia.org/ablu/pagedjs-cli/tree/pdf-outline

No idea how to implement this.

**Comment by MaxMelcher** [comment]
TOC is now available - thanks to @chrPetry 
Outlines are not exported by pupeteer - once they support it, we will support it.
