### ISSUE TITLE
Link to work items from a Wiki page

### ISSUE THREAD

**Issue by AltarBeastiful** [MaxMelcher/AzureDevOps.WikiPDFExport#72]
I would like to see the task from #61 " Link to work items from a Wiki page" implemented.
Could you give pointers for where to start it's implementation ?

**Comment by MaxMelcher** [comment]
That's quite some work - I'd rather see you start with #71 but happy to merge both. 

I briefly added two work items to a project and added them to a wiki:

![image](https://user-images.githubusercontent.com/1029559/125849095-8046ae99-65a3-4b27-88f8-4fee669a9fe1.jpeg)

So we need to check the content of all pages to #(number) and then query the Azure DevOps API to get the title and type of the work item. 
This requires authentication, so we need to provide a PAT token as parameter. 

Not sure how many types of work items there are - but replicating the styles similar to the rendering in the wiki would be nice 😊 
Adding some extra styles to the Stylesheet so people can overwrite them, too. 

Helpful?

**Comment by MaxMelcher** [comment]
merged and released in v3.3.0
