### ISSUE TITLE
Colorize code blocks

### ISSUE THREAD

**Issue by AltarBeastiful** [MaxMelcher/AzureDevOps.WikiPDFExport#73]
Code blocks seem to be properly styled using `<code class="language-xxx">` but not color are shown in the final PDF.
Also the code block could be more outlined like the azure devops wiki style :
![image](https://user-images.githubusercontent.com/3317699/125846457-3e0bc812-e707-45bc-a2c5-ca89fdbd6465.png)

**Comment by MaxMelcher** [comment]
Have you checked the generated html - potentially this is just a styling issue.

**Comment by Jheronymus** [comment]
markdown code blocks are indeed converted to `<pre><code class="language-name"></code></pre>`
in the devopswikistyle.css file there is styling for this. However, this does not do code highlighting. It only styles the block itself. 

If you want individual keyword to look different, they need to have a span tag with a class. Also on DevOps there is a service running that does this. It adds the correct span tags with the applicable styling.

A quick google leads you to https://highlightjs.org/ perhaps there are more out there that can be used readily.

**Comment by MaxMelcher** [comment]
I used highlightjs - it’s JavaScript and a Stylesheet similar to the mermaid and latex thing we already have in place…

Putting it on the list

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AltarBeastiful** [comment]
Just added a PR adding highlight-js that fixes my issue.

Also my first issue with the code blocks appearing white was because of a styling issue.
The `--css` parameter actually replaces the default css. To fix it, I copied the content of `devopswikistyle.css` at the beginning of my custom css file.
