### ISSUE TITLE
Markdown elements in the input are too deeply nested - depth limit exceeded

### ISSUE THREAD

**Issue by yfrindel** [MaxMelcher/AzureDevOps.WikiPDFExport#76]
Hi. I have the following error with an export done with the AzureDevOps.WikiPDFExport plugin
:

System.ArgumentException: Markdown elements in the input are too deeply nested - depth limit exceeded. Input is most likely not sensible or is a very large table.
   at Markdig.Helpers.ThrowHelper.<CheckDepthLimit>g__DepthLimitExceeded|16_0()
   at Markdig.Renderers.RendererBase.WriteChildren(ContainerInline containerInline)
   at Markdig.Renderers.Html.Inlines.DelimiterInlineRenderer.Write(HtmlRenderer renderer, DelimiterInline obj)
   at Markdig.Renderers.MarkdownObjectRenderer`2.Write(RendererBase renderer, MarkdownObject obj)

Any ideas how I can fix the issue please? (the error message is not enough clear, and I don't know where is the problem)

![image](https://user-images.githubusercontent.com/22955005/126319472-c9a4f85d-89e7-4c7a-a3ea-616f3a53f632.png)

**Comment by MaxMelcher** [comment]
Do you have a table on the cobas-configuration page? Could you share that with me?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: yfrindel ***@***.***>
Sent: Tuesday, July 20, 2021 1:54:53 PM
To: MaxMelcher/AzureDevOps.WikiPDFExport ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MaxMelcher/AzureDevOps.WikiPDFExport] Markdown elements in the input are too deeply nested - depth limit exceeded (#76)


Hi. I have the following error with an export done with the AzureDevOps.WikiPDFExport plugin
:

System.ArgumentException: Markdown elements in the input are too deeply nested - depth limit exceeded. Input is most likely not sensible or is a very large table.
at Markdig.Helpers.ThrowHelper.g__DepthLimitExceeded|16_0()
at Markdig.Renderers.RendererBase.WriteChildren(ContainerInline containerInline)
at Markdig.Renderers.Html.Inlines.DelimiterInlineRenderer.Write(HtmlRenderer renderer, DelimiterInline obj)
at Markdig.Renderers.MarkdownObjectRenderer`2.Write(RendererBase renderer, MarkdownObject obj)

Any ideas how I can fix the issue please? (the error message is not enough clear, and I don't know where is the problem)

[image]<https://user-images.githubusercontent.com/22955005/126319472-c9a4f85d-89e7-4c7a-a3ea-616f3a53f632.png>

**Comment by yfrindel** [comment]
don't know if this text is the reason of the failure : 
![image](https://user-images.githubusercontent.com/22955005/126325118-01c064e6-0907-47a5-b8de-76d191f3af07.png)
but I have downloaded again the 5 images in the wiki page, and I put this text in "code" block, and it works now.

**Comment by yfrindel** [comment]
I can confirm you that it's this text the problem (don't know why. Maybe a part of the text is considered as a markdown) : 
![image](https://user-images.githubusercontent.com/22955005/126346542-e77be9bb-d78a-4d83-8830-53360e488395.png)
