### ISSUE TITLE
Qt: Could not initialize OLE (error 80010106)

### ISSUE THREAD

**Issue by Marcel-Baltzer** [MaxMelcher/AzureDevOps.WikiPDFExport#78]
Hi, 

I tried your PDF export and got this error.
Can you tell me what I'm doing wrong?

![image](https://user-images.githubusercontent.com/35496438/130070327-4241e23a-85d9-465e-9de6-1b5440348bae.png)

best wishes
Marcel

**Comment by MaxMelcher** [comment]
Hi Marcel,

That's only a warning - and can be ignored.
Is there no pdf or what is the problem?

Thanks,
Max

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Marcel-Baltzer ***@***.***>
Sent: Thursday, August 19, 2021 2:46:27 PM
To: MaxMelcher/AzureDevOps.WikiPDFExport ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MaxMelcher/AzureDevOps.WikiPDFExport] Qt: Could not initialize OLE (error 80010106) (#78)


Hi,

I tried your PDF export and got this error.
Can you tell me what I'm doing wrong?

[image]<https://user-images.githubusercontent.com/35496438/130070327-4241e23a-85d9-465e-9de6-1b5440348bae.png>

best wishes
Marcel
