### ISSUE TITLE
When exporting the Wiki I expect that I can see almost the same in wiki as in the PDF

### ISSUE THREAD

**Issue by ThorvaldAagaard** [MaxMelcher/AzureDevOps.WikiPDFExport#8]
This is how it looks on my wiki
![image](https://user-images.githubusercontent.com/10560652/64773361-852f1280-d552-11e9-9dbc-20360712c8de.png)

and this is the content in the PDF-file
![image](https://user-images.githubusercontent.com/10560652/64773489-c0314600-d552-11e9-8389-074c8bd041bc.png)

I think the issue might be that the tool is not including the page names as headers in the output, thus making it much more readable

Content of .order is
0.-Introduction
1.-Onboarding
2.-Applications
3.-Architecture
4.-Object-and-data-model
5.-Deployment
9.-Obsolete-systems
and I would expect that as an index in the PDF 

Best regards
Thorvald

**Comment by MaxMelcher** [comment]
actually this should be the case. when did you try it the last time? 
Maybe try the --heading parameter.

**Comment by ThorvaldAagaard** [comment]
It is long time since I worked on the project, where we used the tool, and I will probably no get access to the documentation again, so it is ok to close this, if you think it is working ok
