### ISSUE TITLE
Depth limit

### ISSUE THREAD

**Issue by surfarri** [MaxMelcher/AzureDevOps.WikiPDFExport#81]
Receive the following error when trying against my cloned wiki:

ERR: Something bad happend.
System.ArgumentException: Markdown elements in the input are too deeply nested - depth limit exceeded. Input is most likely not sensible or is a very large table.
   at Markdig.Helpers.ThrowHelper.<CheckDepthLimit>g__DepthLimitExceeded|16_0()
   at Markdig.Renderers.RendererBase.WriteChildren(ContainerInline containerInline)
   at Markdig.Renderers.Html.Inlines.DelimiterInlineRenderer.Write(HtmlRenderer renderer, DelimiterInline obj)

**Comment by MaxMelcher** [comment]
Hey Scott,

Do you have text with | as separator?
In #76 we had the same issue.

Thanks,
Max

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Scott Farriss ***@***.***>
Sent: Monday, August 30, 2021 6:17:05 PM
To: MaxMelcher/AzureDevOps.WikiPDFExport ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MaxMelcher/AzureDevOps.WikiPDFExport] Depth limit (#81)


Receive the following error when trying against my cloned wiki:

ERR: Something bad happend.
System.ArgumentException: Markdown elements in the input are too deeply nested - depth limit exceeded. Input is most likely not sensible or is a very large table.
at Markdig.Helpers.ThrowHelper.g__DepthLimitExceeded|16_0()
at Markdig.Renderers.RendererBase.WriteChildren(ContainerInline containerInline)
at Markdig.Renderers.Html.Inlines.DelimiterInlineRenderer.Write(HtmlRenderer renderer, DelimiterInline obj)

**Comment by surfarri** [comment]
Hi Max,

Within the contents of the wiki?  If so, then likely yes.  Our wiki is very large and there is probably code/data samples along the way that have the pipe character.  Was there a solution for #76, or was the fix just to find and remove those characters from the content?

Thanks
Scott

**Comment by MaxMelcher** [comment]
He wrapped the text containing the separator in a code block.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MaxMelcher** [comment]
You can also run it with --verbose flag. Then you should locate the markdown file and potentially pinpoint the error.

**Comment by surfarri** [comment]
OK, I'll try to run it that way.  There may be too many locations to try and correct in the wiki where the problem occurs, but I really like the tool for my other smaller wikis.
Thanks Max!

**Comment by MaxMelcher** [comment]
If you have an example where it fails, provide it please so we can fix it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by equitably** [comment]
This seems to be a markdig issue.  Here is an example of a table that fails:

```
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
Do|Re|Mi|Fa|Sol|La
```
