### ISSUE TITLE
Image sizing width

### ISSUE THREAD

**Issue by shep1987** [MaxMelcher/AzureDevOps.WikiPDFExport#82]
Hey Max,

Related to: https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/issues/30
I found another format it would be great if you could support

Relative Pictures with Width only
![image.png](/.attachments/500.png =50%x)

Thanks

Shaun

**Comment by MaxMelcher** [comment]
Doable, I will add it to v4
