### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by Nyhtfury** [MaxMelcher/AzureDevOps.WikiPDFExport#85]
Possibly related to #28 

When I add screen captures directly into the Azure DevOps wiki editor, it automatically adds a .png file to /.attachments/image-<guid>.png and commits once I save.

I'm trying to generate a PDF via Richard Fennell's extension and I'm generating a pdf but images are broken just like they are in #28. I've taken an additional step to rule out that marketplace extension by cloning the wiki repo locally and attempting to use the .exe from the latest release (4.0.3).

Image links are still broken (examples) if I don't specify the attachments path:
```
![image.png](/.attachments/image-3b66b830-e48b-47db-9de3-98a73f829156.png)
![image.png](/.attachments/image-8b34b0d2-0f2c-464d-bd65-dde464880467.png)
```
![image.png](/.attachments/image-3b66b830-e48b-47db-9de3-98a73f829156.png)
![image.png](/.attachments/image-8b34b0d2-0f2c-464d-bd65-dde464880467.png)

Fortunately, if I explicitly provide `--attachments-path .attachments` it works, but I thought it was only necessary if I was converting a sub folder.

**Comment by MaxMelcher** [comment]
potentially fixed f726d3da5c32351bb47d02c07b60b7f89a34dc4d
