### ISSUE TITLE
The remote party closed the WebSocket connection without completing the close handshake

### ISSUE THREAD

**Issue by yfrindel** [MaxMelcher/AzureDevOps.WikiPDFExport#86]
Hi

I hava an unexpected error at the end of the process :
![image](https://user-images.githubusercontent.com/22955005/146188862-5f6d2351-b5e6-4957-a5ac-08c2a47bdbc2.png)
Someone could help me please?

Thanks

**Comment by yfrindel** [comment]
By chance, do you have an idea of the reason of the issue? and how to fix?

**Comment by MaxMelcher** [comment]
sorry for the delay.
What parameters are you using? Does the build server have internet access?
