### ISSUE TITLE
Blank/Empty output pdf

### ISSUE THREAD

**Issue by COWI-FIBR** [MaxMelcher/AzureDevOps.WikiPDFExport#88]
I'm using the [Richard Fennell WikiPDFExportTask](https://github.com/rfennell/AzurePipelines/wiki/WIKI-PdfExport-Task) extension, but was redirected here for this issue.

PdfExport task executes fine, but the generated pdf is blank. Opening the file, the page is white, nothing else.

From the log of executing WikiPdfExportTask@2 step:  
> A filename '**20220126.3_project_releasenote.md**' in the folder '**/home/vsts/work/1/s**' has been requested so only processing that file
> Adding the verbose flag to increase logging
> Changing folder to /home/vsts/work/1/s
> Using command '"/home/vsts/work/_temp/azuredevops-export-wiki" **-p "/home/vsts/work/1/s"** **-s "20220126.3_project_releasenote.md"** **-o "/home/vsts/work/1/s/20220126.3_project_releasenote.pdf"** -v'
> Reading .order file in directory /home/vsts/work/1/s
> Converting Markdown to HTML
> No CSS specified, using devopswikistyle.css
> Converting HTML to PDF
> PDF created at: **/home/vsts/work/1/s/20220126.3_project_releasenote.pdf**  

I've added a Bash step to `cat` the 20220126.3_project_releasenote.md file, to verify its content, and list the content of System.DefaultWorkingDirectory to verify that both files are there.

> 4.0K -rw-r--r-- 1 vsts docker 1022 Jan 26 14:14 20220126.3_project_releasenote.md
> 4.0K -rw-r--r-- 1 vsts docker 857 Jan 26 14:14 20220126.3_project_releasenote.pdf

Anyone else experienced that the output pdf is blank?

**Comment by MaxMelcher** [comment]
I have not tested converting a single file, at least in a while. 
Did you create this file through Azure DevOps or by yourself?

**Comment by COWI-FIBR** [comment]
The file was generated using the DevOps extension [GenerateReleaseNotes Node based Cross Platform Task](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task) by rfennell.
In the meantime, I've found another way of converting the file to pdf.

**Comment by MaxMelcher** [comment]
I got how you convert the markdown file - but how did you create it? By yourself or with Azure DevOps wiki?

**Comment by MaxMelcher** [comment]
thanks for reporting this and this is fixed in the next release. 
I assume you provided the -s parameter but not the -p parameter, somehow both were required. 
I fixed that so it it using only the -s parameter now.
