### ISSUE TITLE
Allow background styling

### ISSUE THREAD

**Issue by bvermolen** [MaxMelcher/AzureDevOps.WikiPDFExport#91]
When generating the pdf-document, the PDFOptions do not specify the "PrintBackground" option. By default this is set to false.

This setting prevents us to apply background-styling on headers. Is is possible to make it configurable?

**Comment by MaxMelcher** [comment]
Sure, could you please contribute a pull request?

**Comment by bvermolen** [comment]
@MaxMelcher, see #92.

**Comment by MaxMelcher** [comment]
Thanks @bvermolen!
