### ISSUE TITLE
Table of Contents - Code with # comments cause errors

### ISSUE THREAD

**Issue by Diom** [MaxMelcher/AzureDevOps.WikiPDFExport#94]
V4.2.0
--globaltoc enabled

Code section like this:
![image](https://user-images.githubusercontent.com/1903065/153407908-505821ee-08c3-4533-b15d-cc37f7f3a525.png)

Results in an incorrect table:
![image](https://user-images.githubusercontent.com/1903065/153408035-3ee303c6-1264-416c-b35c-69b38c910c56.png)

**Comment by MaxMelcher** [comment]
@chrPetry could you please have a look?

**Comment by chrPetry** [comment]
Ahh yes I forgot code sections.
Working already on filtering them
