### ISSUE TITLE
Internal Links are not working

### ISSUE THREAD

**Issue by Diom** [MaxMelcher/AzureDevOps.WikiPDFExport#97]
Issue:

Links to other sections of the wiki (not deep-linked) are not clickable in the generated PDF

![image](https://user-images.githubusercontent.com/1903065/154966127-07904f9e-8b58-49fd-bfe5-c5024ca277d9.png)

**To Reproduce:**

Add a link to a wiki MD page:

~~~markdown
I want to test if this [link](/Admin-Layout-and-Customization) works
~~~

Run the build (ctrl+f5)

**Expected**

Link to internal section of the PDF will work.

**Actual**

The text is styled as a link but does not work.

**Example**

Added the above to the test wiki in the repo and built the project. This was output in the console:

~~~html
<div style='page-break-after: always;'><h1>Another Page</h1><a id="another-page">&nbsp;</a><h2 id="another-page-here">Another Page Here</h2>
<p>I want to test if this <a href="/Admin-Layout-and-Customization">link</a> works</p>
</div>
  html:
<h1>Admin Layout and Customization</h1><a id="admin-layout-and-customization">&nbsp;</a><h2 id="smileys">Smileys</h2>
~~~

Attached PDF the link does not work (I took out the images at the top of the page for clarity in the console

[export.pdf](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/files/8109837/export.pdf)

**Comment by Diom** [comment]
Looks like this section is failing:

~~~cs
                        fileInfo = new FileInfo($"{absPath}.md");
                        if (fileInfo.Exists && fileInfo.Extension.Equals(".md", StringComparison.InvariantCultureIgnoreCase))
                        {
                            isMarkdown = true;
                        }

                        //only markdown files get a pdf internal link
                        if (isMarkdown)
                        {
~~~

For some reason, in the `absPath` there is a ".wiki" being added to the parent folder? This causes the file to "not exist" and not get treated as an internal link.

**Comment by Diom** [comment]
~~~cs
                    var split = _path.Split(".wiki");
                    _rootWikiPath = split[0].IsNullOrEmpty() ? _path : split[0] + ".wiki";
~~~

added there.

Changing to this makes it work:

~~~cs
                    var split = _path.Split(".wiki");
                    _rootWikiPath = _path; //split[0].IsNullOrEmpty() ? _path : split[0] + ".wiki";
~~~

It looks like the work added to make the internal links work when exporting a sub-section broke the links. It made a bad assumption that ALL wiki have '.wiki' in the path, which is only true of the default wikis. A better mechanism to detect the root would be to use the path to the .attachments page. 

I will look into that once I have my customer doc updates done!

**Comment by Diom** [comment]
Solved it properly by doing this:

~~~cs
    public static DirectoryInfo FindNearestParentAttachmentsDirectory(DirectoryInfo exportBase)
    {
        DirectoryInfo[] gitDirs = exportBase.GetDirectories("./.attachments");
        if(gitDirs != null && gitDirs.Length > 0) {
            return gitDirs[0].Parent;
        }
        if (null != exportBase.Parent) {
            return FindNearestParentAttachmentsDirectory(exportBase.Parent);
        }
        throw new WikiPdfExportException("Failed to locate the base of the Wiki using attachment detection");
    }
~~~

will try to find time to test it PRed soon

**Comment by Diom** [comment]
PR #98 opened

**Comment by MaxMelcher** [comment]
wow - intensive review and addition - THANK YOU @Diom
